language: node_js
node_js:
  - "stable"
  
script:
  - npm run lint
  - npm run build
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $h
  local_dir: dist
  target_branch: master
  on:
    branch: source